# .mdformat.toml
#
wrap = "keep"       # possible values: {"keep", "no", INTEGER}
number = true       # possible values: {false, true}
end_of_line = "lf"  # possible values: {"lf", "crlf", "keep"}
validate = true     # options: {false, true}

# extensions = [      # options: a list of enabled extensions (default: all installed are enabled)
#     "gfm",
#     "toc",
# ]

# codeformatters = [  # options: a list of enabled code formatter languages (default: all installed are enabled)
#     "python",
#     "json",
# ]

exclude = []          # options: a list of file path pattern strings
